name: CI Build

on:
  push:
    branches:
      - dev

jobs:
  version:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - uses: actions/checkout@master

      - name: Grants permisions
        run: chmod +x ./bin/version.sh

      - name: Change version
        id: version
        run: echo "new_version=$(./bin/version.sh "${{ github.event.head_commit.message }}")" >> $GITHUB_OUTPUT

      - name: Update version file
        run: |
          echo ${{ steps.version.outputs.new_version }}
