name: PRUEBAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

          proxy_host: ${{ secrets.DEPLOY_PROXY_HOST }}
          proxy_port: ${{ secrets.DEPLOY_PROXY_PORT }}
          proxy_username: ${{ secrets.DEPLOY_PROXY_USERNAME }}
          proxy_key: ${{ secrets.DEPLOY_PROXY_KEY }}

          script: |
            docker ps -a
          #cd database-service
          #git pull origin main
          
          #docker compose down
          #${{ secrets.DEPLOY_ENV }} VERSION=1.1.1 docker compose up -d