name: PRUEBAS

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4

      - id: version
        run: echo "new_version=v1.1.2" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy docker
        uses: appleboy/ssh-action@v1.0.3
        with:

          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

          proxy_host: ${{ secrets.DEPLOY_PROXY_HOST }}
          proxy_port: ${{ secrets.DEPLOY_PROXY_PORT }}
          proxy_username: ${{ secrets.DEPLOY_PROXY_USERNAME }}
          proxy_key: ${{ secrets.DEPLOY_PROXY_KEY }}

          envs: PG_USER,PG_PASSWORD,PG_ADMIN_EMAIL,PG_ADMIN_PASSWORD,APP_VERSION

          script: |
            echo $APP_VERSION

        env:
          PG_USER: ${{secrets.PG_USER}}
          PG_PASSWORD: ${{secrets.PG_PASSWORD}}
          PG_ADMIN_EMAIL: ${{secrets.PG_ADMIN_EMAIL}}
          PG_ADMIN_PASSWORD: ${{secrets.PG_ADMIN_PASSWORD}}
          APP_VERSION: ${{ needs.test.outputs.new_version }}
 